### ISSUE TITLE
Details missing/incorrect

### ISSUE THREAD

**Issue by seashadowcool** [ekspla/Read-Symbian-SportsTracker-file#15]
First, thanks for your project! I'm still using my Nokia 700 with sports tracker, but since a few months we were not able to connect to sports tracker service (I think they have change their connection API).

So,
When importing gpx files converted, some details are erronous :
- start time
- date
- duration
- energy (kcal)

Here is an example :
<img width="649" alt="Import example" src="https://user-images.githubusercontent.com/84711482/119332133-79cd3d80-bc88-11eb-9dbc-3ef2d8311aec.png">

Incorrect details : 
 - Start time : 12:04 -> instead of 16:01
 - duration : 0:00:00 -> instead of 00:26:01
 - energy : -3647410 -> instead of 381.6 kcal
 - date : 24 may -> instead of 20 may

It will be great to make a update. Thanks

**Comment by ekspla** [comment]
Dear seashadowcool,

can you upload the .dat file so that I can investigate it in detail?

**Comment by seashadowcool** [comment]
I have already deleted the dat file. The next time I have an activity, I'll give you the dat file with all the details from the phone and the same from the website (importing the gpx).

**Comment by ekspla** [comment]
> Start time : 12:04 -> instead of 16:01
> duration : 0:00:00 -> instead of 00:26:01

These two might be related to timezone handling code inside **www.sports-tracker.com**, given that you were in UTC+4 timezone.  But I am still not sure about the following part:

>  date : 24 may -> instead of 20 may.

So, it's better to have all the data, incl. the raw W*.dat, before investigation.

**Comment by ekspla** [comment]
@seashadowcool 
I have created an account on sports-tracker.com and uploaded/tested gpx files.

I found that the date/time shown was not those of the gpx but those when I uploaded the gpx.  They ignore timestamps completely.  The duration was show as 0:00:00 (not calculated automatically).  One has to edit the start time, duration, etc. 
on the web site.

I am sure this issue is not caused by my code, but is caused by the web site.  So, I will close the case.
